splines:
  - a:     0.0
    b:     0.0
    c:     0.0
    x_min: 0.0
    x_max: 5.0
    frame_id: map

  - a:     -0.25
    b:      0.0
    c:      2.0
    x_min: -2.0
    x_max: 2.0
    frame_id: map

  # adicione mais blocos - cada um vira uma spline
